version: '3.4'

services:
  nginx:
    #restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "80:80"
    depends_on:
      - "testexercise"
  postgres: 
    image: 'postgres:latest'
    #environment:
      #- POSTGRES_PASSWORD=postgres_password
  redis-server:
    image: 'redis:latest'
  testexercise:
    restart: always #on-failure | unless-stopped | "no"
    image: testexercise
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000"
    environment:
      REDIS_URL: redis-server:6379
     
